version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./core/.env
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - backend

  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: always
    env_file:
      - ./core/.env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:5.0
    container_name: redis
    restart: always
    env_file:
      - ./core/.env
    command: sh -c 'redis-server --requirepass "${REDIS_PASSWORD}"'
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - backend

  core:
    build:
      context: ./core
      target: dev
    container_name: core_container
    ports:
      - "4000:4000"
    env_file:
      - ./core/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./core:/app
    command: yarn start:dev
    networks:
      - backend

  ai:
    build:
      context: ./ai
    container_name: ai_service
    ports:
      - "8080:8080"
    env_file:
      - ./ai/.env
    depends_on:
      - core
      - ollama
    networks:
      - backend

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    env_file:
      - ./ai/.env
    volumes:
      - ollama:/root/.ollama
      - ./ai/run_model.sh:/run_model.sh:ro
    entrypoint: ["/bin/bash", "-c", "/run_model.sh"]
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:
  ollama:
  minio_data:

networks:
  backend:
