FROM golang:1.23 AS builder

WORKDIR /app

COPY . .

RUN go mod tidy


RUN go test -cover ./...

RUN go build -o ai-service ./cmd/main.go

FROM gcr.io/distroless/base-debian12

COPY --from=builder /app/ai-service /ai-service

CMD ["/ai-service"]
