FROM golang:1.23 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o llm-service ./cmd/main.go

FROM gcr.io/distroless/base-debian12

COPY --from=builder /app/llm-service /llm-service

CMD ["/llm-service"]
